# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: justinh@alumni.harvard.edu
author_name: mybffjustin
cloud_provider: vercel
contract_name: hello_world
preset_name: production
project_name: joltkin

