# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: justinh@alumni.harvard.edu
author_name: mybffjustin
cloud_provider: vercel
preset_name: production
project_name: joltkin-frontend

